### ISSUE TITLE
Python package release tracking issue

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-python#14]
Tracking issue for first and subsequent Python package releases.

### Stage 1: first alpha test release
- [x] Add changelog file (no mono required yet)
- [x] #3
- [x] #16 
- [x] https://github.com/appsignal/mono/issues/54
- [x] #29
  - Blocked on desired package name, now available as "appsignal-beta".

### Stage 2: Beta testers
- [x] https://github.com/appsignal/mono/issues/50
- [x] #18 
- [x] #30
- [x] #36 
- [x] https://github.com/appsignal/appsignal-docs/issues/1284
- [x] #34 
- [x] #5 - small issue
- [x] #42 
    - Python related decision, https://github.com/appsignal/appsignal-python/issues/14#issuecomment-1540092313seee 
- [x] #43
- [x] #72 
- [x] #69 
- [x] https://github.com/appsignal/appsignal-python/pull/68
- [x] https://github.com/appsignal/appsignal-docs/issues/1285
- [x] https://github.com/appsignal/appsignal-server/issues/9532
- [x] https://github.com/appsignal/appsignal-agent/issues/1004
- [x] Internal testing

### Stage 3: 1.0 release
- [x] #12 
- [x] #19 
- [ ] #13 
- [ ] #49
- [ ] Add to blog:
  - [ ] Add a Python category/tag?
- [x] https://github.com/appsignal/appsignal-agent/issues/999

### Stage 4: Feature parity
- [ ] #7
- [ ] #8
- [ ] #32

**Comment by tombruijn** [comment]
I think we should also decide on issue https://github.com/appsignal/integration-guide/issues/73 and update the Python package to match before we ship a first release–that's not a prerelease–to the production registry.

**Comment by tombruijn** [comment]
Closing this tracking issue. We're close to a 1.0 release. The remaining linked open issues can be picked up individually according to our cycle planning.
